version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    depends_on:
        - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=MyDatabaseSecret123
    ports:
    - "1433:1433"
