version: "3.4"

services:
    WebAPI:
        build:
          context: .
          dockerfile: WebAPI/Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - SqlServerDb

    SqlServerDb:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "8001:80"

        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"